import { Vehicle, Trip, InventoryItem, PayrollRecord, SystemNotification, ActivityItem, AttendanceRecord, PODRecord, DriverRecord } from '../types';

export const mockVehicles: Vehicle[] = [];
export const mockTrips: Trip[] = [];

export const mockInventory: InventoryItem[] = [
  {
    id: 'inv-demo-1',
    itemName: 'Industrial Steel Sheet (Grade 304)',
    sku: 'SKU-10029',
    category: 'Raw Materials',
    unit: 'Pieces',
    quantity: 450,
    minimumQuantity: 100,
    reservedStock: 25,
    maximumStockLevel: 1000,
    purchasePrice: 1200,
    sellingPrice: 1850,
    warehouse: 'Main Warehouse A',
    storageLocation: 'Shelf A-4, Rack 2',
    supplier: 'Apex Steel Corp Ltd',
    status: 'Active',
    description: 'High-grade cold-rolled industrial sheet metal used for chassis fabrication.',
  },
  {
    id: 'inv-demo-2',
    itemName: 'Hydraulic Cylinder Seal Kit',
    sku: 'SKU-20481',
    category: 'Assemblies',
    unit: 'Packs',
    quantity: 18,
    minimumQuantity: 25,
    reservedStock: 5,
    maximumStockLevel: 200,
    purchasePrice: 450,
    sellingPrice: 720,
    warehouse: 'Secondary Bay B',
    storageLocation: 'Bin 12-B',
    supplier: 'Fluid Tech Hydraulics',
    status: 'Active',
    description: 'Replacement seal kit for heavy-duty hydraulic rams and tilt cylinders.',
  },
  {
    id: 'inv-demo-3',
    itemName: 'Engine Synthetic Lubricant 15W-40',
    sku: 'SKU-30912',
    category: 'Lubricants',
    unit: 'Litre',
    quantity: 0,
    minimumQuantity: 50,
    reservedStock: 0,
    maximumStockLevel: 500,
    purchasePrice: 320,
    sellingPrice: 550,
    warehouse: 'Central Depot',
    storageLocation: 'Drum Storage C',
    supplier: 'Bharat Petroleum Fleet Supplies',
    status: 'Active',
    description: 'Heavy duty commercial diesel engine oil for long-haul fleet trucks.',
  },
  {
    id: 'inv-demo-4',
    itemName: 'Commercial Fleet Brake Pads (Front)',
    sku: 'SKU-40115',
    category: 'Tools & Equipment',
    unit: 'Boxes',
    quantity: 120,
    minimumQuantity: 30,
    reservedStock: 10,
    maximumStockLevel: 300,
    purchasePrice: 850,
    sellingPrice: 1400,
    warehouse: 'Main Warehouse A',
    storageLocation: 'Shelf C-1',
    supplier: 'Bosch Auto Systems',
    status: 'Active',
    description: 'OEM grade ceramic front brake pad set for heavy cargo trucks.',
  },
  {
    id: 'inv-demo-5',
    itemName: 'Heavy Corrugated Packing Boxes (XL)',
    sku: 'SKU-50220',
    category: 'Packaging',
    unit: 'Boxes',
    quantity: 850,
    minimumQuantity: 200,
    reservedStock: 50,
    maximumStockLevel: 2000,
    purchasePrice: 45,
    sellingPrice: 85,
    warehouse: 'Packaging Dock 4',
    storageLocation: 'Pallet Zone E',
    supplier: 'Kraft Packaging Solutions',
    status: 'Active',
    description: '3-ply reinforced shipping boxes for parcel and goods transport.',
  },
];

export const mockPayroll: PayrollRecord[] = [
  {
    id: 'pay-demo-1',
    employee: 'Harpreet Singh',
    basicSalary: 35000,
    overtime: 4500,
    bonus: 2000,
    allowance: 1000,
    deduction: 500,
    tax: 1200,
    finalSalary: 41500,
    paymentStatus: 'Paid',
    paymentDate: '2026-08-01',
  },
  {
    id: 'pay-demo-2',
    employee: 'Rajesh Kumar',
    basicSalary: 28000,
    overtime: 3200,
    bonus: 1500,
    allowance: 500,
    deduction: 0,
    tax: 500,
    finalSalary: 32700,
    paymentStatus: 'Pending',
  },
  {
    id: 'pay-demo-3',
    employee: 'Vikram Sharma',
    basicSalary: 42000,
    overtime: 6000,
    bonus: 3500,
    allowance: 1500,
    deduction: 800,
    tax: 1800,
    finalSalary: 51500,
    paymentStatus: 'Paid',
    paymentDate: '2026-08-01',
  },
  {
    id: 'pay-demo-4',
    employee: 'Amit Patel',
    basicSalary: 25000,
    overtime: 1800,
    bonus: 1000,
    allowance: 0,
    deduction: 0,
    tax: 300,
    finalSalary: 27800,
    paymentStatus: 'Pending',
  },
  {
    id: 'pay-demo-5',
    employee: 'Suresh Verma',
    basicSalary: 31000,
    overtime: 2500,
    bonus: 2000,
    allowance: 800,
    deduction: 400,
    tax: 900,
    finalSalary: 35500,
    paymentStatus: 'Paid',
    paymentDate: '2026-08-02',
  },
];

export const mockAttendance: AttendanceRecord[] = [];
export const mockNotifications: SystemNotification[] = [];
export const mockActivities: ActivityItem[] = [];
export const mockPODs: PODRecord[] = [];

export const mockDrivers: DriverRecord[] = [];

