import * as XLSX from 'xlsx';

export interface InventoryExportData {
  id: string;
  itemName: string;
  category: string;
  sku: string;
  productId?: string;
  barcode?: string;
  subCategory?: string;
  brand?: string;
  unit?: string;
  warehouse: string;
  storageLocation?: string;
  supplier: string;
  description?: string;
  purchasePrice: number;
  sellingPrice: number;
  quantity: number;
  reservedStock?: number;
  minimumQuantity: number;
  maximumStockLevel?: number;
  reorderLevel?: number;
  batchNumber?: string;
  expiryDate?: string;
  manufacturingDate?: string;
  lastRestockedDate?: string;
  remarks?: string;
  status?: string;
  companyId?: string;
  ownerId?: string;
  createdAt?: string;
  updatedAt?: string;
}

export const downloadInventoryExcel = (data: InventoryExportData[]) => {
  const wb = XLSX.utils.book_new();

  // Get current user and company info
  const userJson = localStorage.getItem('smartops_user');
  const userObj = userJson ? JSON.parse(userJson) : null;
  const username = userObj?.fullName || 'System Administrator';
  const companyName = userObj?.companyName || 'SmartOps Logistics';
  
  const dateStr = new Date().toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'medium'
  });

  // Calculate Metrics for Sheet 1: Inventory Summary
  const totalProducts = data.length;
  const uniqueCategories = new Set(data.map(d => d.category)).size;
  const totalStockQuantity = data.reduce((acc, curr) => acc + (curr.quantity || 0), 0);
  const totalInventoryValue = data.reduce((acc, curr) => acc + ((curr.quantity || 0) * (curr.purchasePrice || 0)), 0);
  
  const lowStockCount = data.filter(d => (d.quantity || 0) <= (d.minimumQuantity || 0) && (d.quantity || 0) > 0).length;
  const outOfStockCount = data.filter(d => (d.quantity || 0) === 0).length;
  const reorderLevelDefault = 10;
  const reorderRequiredCount = data.filter(d => (d.quantity || 0) <= (d.reorderLevel || reorderLevelDefault)).length;

  // ----------------------------------------------------
  // SHEET 1: INVENTORY SUMMARY
  // ----------------------------------------------------
  const summaryAOA = [
    ['SMARTOPS ENTERPRISE SOLUTIONS'],
    ['INVENTORY EXECUTIVE SUMMARY LEDGER'],
    [''],
    ['Company Name:', companyName],
    ['Generated On:', dateStr],
    ['Generated By:', username],
    ['Scope:', 'Live Database Inventory Status Report'],
    [''],
    ['KEY PERFORMANCE INDICATORS'],
    ['Metric Description', 'Value', 'Status / Target'],
    ['Total Unique Products', totalProducts, 'Active SKU Count'],
    ['Total Categories', uniqueCategories, 'Product Classification Groups'],
    ['Total Stock Quantity', totalStockQuantity, 'Units In Stock'],
    ['Total Inventory Value (Cost)', totalInventoryValue, 'INR Value (Purchase Price Basis)'],
    ['Low Stock SKUs', lowStockCount, lowStockCount > 0 ? '⚠️ Action Required' : '✅ Optimal'],
    ['Out of Stock SKUs', outOfStockCount, outOfStockCount > 0 ? '🚨 Critical Replenishment' : '✅ Healthy'],
    ['Reorder Needed Count', reorderRequiredCount, reorderRequiredCount > 0 ? 'Order Placements Due' : '✅ All Clear'],
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryAOA);

  // Set column widths for summary sheet
  wsSummary['!cols'] = [{ wch: 30 }, { wch: 25 }, { wch: 35 }];
  
  // Format total inventory value cell (B14 -> r: 13, c: 1)
  const totalValCellRef = XLSX.utils.encode_cell({ r: 13, c: 1 });
  if (wsSummary[totalValCellRef]) {
    wsSummary[totalValCellRef].z = '₹#,##0.00';
    wsSummary[totalValCellRef].t = 'n';
  }
  
  // Format total stock qty cell (B13 -> r: 12, c: 1)
  const totalQtyCellRef = XLSX.utils.encode_cell({ r: 12, c: 1 });
  if (wsSummary[totalQtyCellRef]) {
    wsSummary[totalQtyCellRef].z = '#,##0';
    wsSummary[totalQtyCellRef].t = 'n';
  }

  XLSX.utils.book_append_sheet(wb, wsSummary, 'Inventory Summary');

  // ----------------------------------------------------
  // SHEET 2: COMPLETE INVENTORY
  // ----------------------------------------------------
  const headers = [
    'Product Name',           // A (col 0)
    'Product ID',             // B (col 1)
    'SKU',                    // C (col 2)
    'Barcode',                // D (col 3)
    'Category',               // E (col 4)
    'Sub Category',           // F (col 5)
    'Brand',                  // G (col 6)
    'Unit',                   // H (col 7)
    'Warehouse',              // I (col 8)
    'Storage Location',       // J (col 9)
    'Supplier Name',          // K (col 10)
    'Purchase Price',         // L (col 11)
    'Selling Price',          // M (col 12)
    'Current Stock Quantity', // N (col 13)
    'Reserved Stock',         // O (col 14)
    'Available Stock',        // P (col 15) -> Formula
    'Minimum Stock Level',    // Q (col 16)
    'Maximum Stock Level',    // R (col 17)
    'Reorder Level',          // S (col 18)
    'Reorder Status',         // T (col 19) -> Formula
    'Stock Status',           // U (col 20) -> Formula
    'Last Restocked Date',    // V (col 21)
    'Last Updated',           // W (col 22)
    'Expiry Date',            // X (col 23)
    'Batch Number',           // Y (col 24)
    'Manufacturing Date',     // Z (col 25)
    'Total Inventory Value',  // AA (col 26) -> Formula
    'Created By',             // AB (col 27)
    'Remarks',                // AC (col 28)
    'Status'                  // AD (col 29)
  ];

  const inventoryRows: any[][] = [];

  data.forEach((item, index) => {
    const rowNum = index + 2; // Rows are 1-indexed, and header is row 1
    const lastUpdatedDate = item.updatedAt ? new Date(item.updatedAt).toLocaleDateString() : new Date().toLocaleDateString();

    const row = [
      item.itemName || '', // A
      item.productId || item.id || '', // B
      item.sku || '', // C
      item.barcode || item.sku || '', // D
      item.category || '', // E
      item.subCategory || 'General', // F
      item.brand || 'SmartOps', // G
      item.unit || 'Pieces', // H
      item.warehouse || '', // I
      item.storageLocation || 'Warehouse Floor', // J
      item.supplier || '', // K
      item.purchasePrice || 0, // L
      item.sellingPrice || 0, // M
      item.quantity || 0, // N
      item.reservedStock || 0, // O
      
      // Available Stock (P): Formula = Current Stock - Reserved Stock
      { t: 'n', f: `N${rowNum}-O${rowNum}` }, // P
      
      item.minimumQuantity || 0, // Q
      item.maximumStockLevel || 1000, // R
      item.reorderLevel || 10, // S
      
      // Reorder Status (T): Formula = IF(N <= S, "Yes", "No")
      { t: 's', f: `IF(N${rowNum}<=S${rowNum},"Yes","No")` }, // T
      
      // Stock Status (U): Formula = IF(N=0, "🔴 Out of Stock", IF(N<=Q, "🟡 Low Stock", "🟢 In Stock"))
      { t: 's', f: `IF(N${rowNum}=0,"🔴 Out of Stock",IF(N${rowNum}<=Q${rowNum},"🟡 Low Stock","🟢 In Stock"))` }, // U
      
      item.lastRestockedDate || lastUpdatedDate, // V
      lastUpdatedDate, // W
      item.expiryDate || 'N/A', // X
      item.batchNumber || 'N/A', // Y
      item.manufacturingDate || 'N/A', // Z
      
      // Total Inventory Value (AA): Formula = Current Stock * Purchase Price
      { t: 'n', f: `N${rowNum}*L${rowNum}` }, // AA
      
      username, // AB
      item.remarks || item.description || '', // AC
      item.status || 'Active' // AD
    ];
    
    inventoryRows.push(row);
  });

  // Build Sheet
  const wsData = XLSX.utils.aoa_to_sheet([headers]);
  
  // Write rows manually to support formats and formula cells
  inventoryRows.forEach((row, rIndex) => {
    const rowIdx = rIndex + 1; // 1-indexed offset for header row
    row.forEach((cellVal, cIndex) => {
      const cellRef = XLSX.utils.encode_cell({ r: rowIdx, c: cIndex });
      
      if (cellVal && typeof cellVal === 'object' && ('f' in cellVal)) {
        wsData[cellRef] = cellVal;
      } else {
        const t = typeof cellVal === 'number' ? 'n' : 's';
        wsData[cellRef] = { t, v: cellVal };
      }

      // Add format to price columns (L: 11, M: 12)
      if (cIndex === 11 || cIndex === 12) {
        wsData[cellRef].z = '₹#,##0.00';
      }
      
      // Add format to quantity columns (N: 13, O: 14, P: 15, Q: 16, R: 17, S: 18)
      if (cIndex >= 13 && cIndex <= 18) {
        wsData[cellRef].z = '#,##0';
      }
      
      // Add format to Total Value column (AA: 26)
      if (cIndex === 26) {
        wsData[cellRef].z = '₹#,##0.00';
      }
    });
  });

  // Add Totals row at the bottom
  const lastRow = inventoryRows.length + 1;
  const totalsRowIndex = lastRow;
  
  wsData['!ref'] = `A1:AD${totalsRowIndex + 1}`;

  const totalsCells = [
    { c: 0, v: 'TOTAL ENTERPRISE STOCK' }, // A: Title
    { c: 13, f: `SUM(N2:N${lastRow})` },   // N: Total Current Stock
    { c: 14, f: `SUM(O2:O${lastRow})` },   // O: Total Reserved Stock
    { c: 15, f: `SUM(P2:P${lastRow})` },   // P: Total Available Stock
    { c: 26, f: `SUM(AA2:AA${lastRow})` }  // AA: Total Inventory Value
  ];

  totalsCells.forEach(cellDef => {
    const cellRef = XLSX.utils.encode_cell({ r: totalsRowIndex, c: cellDef.c });
    if ('f' in cellDef) {
      wsData[cellRef] = { t: 'n', f: cellDef.f };
      if (cellDef.c === 26) {
        wsData[cellRef].z = '₹#,##0.00';
      } else {
        wsData[cellRef].z = '#,##0';
      }
    } else {
      wsData[cellRef] = { t: 's', v: cellDef.v };
    }
  });

  // Freeze first row
  wsData['!views'] = [{ state: 'frozen', ySplit: 1 }];

  // Enable Autofilters
  wsData['!autofilter'] = {
    ref: `A1:AD${lastRow}`
  };

  // Auto column widths
  const colWidths = headers.map((header, colIndex) => {
    let maxLen = header.length;
    for (let r = 1; r <= lastRow; r++) {
      const cellRef = XLSX.utils.encode_cell({ r, c: colIndex });
      const cell = wsData[cellRef];
      let val = '';
      if (cell) {
        if (cell.v !== undefined) val = String(cell.v);
        else if (cell.f !== undefined) val = 'FormulaResult';
      }
      if (val.length > maxLen) maxLen = val.length;
    }
    return { wch: Math.max(maxLen + 3, 11) };
  });
  wsData['!cols'] = colWidths;

  XLSX.utils.book_append_sheet(wb, wsData, 'Complete Inventory');

  // ----------------------------------------------------
  // SHEET 3: ANALYTICS
  // ----------------------------------------------------
  // Aggregate Category Data
  const categoryMap = new Map<string, { qty: number; val: number }>();
  data.forEach(item => {
    const cat = item.category || 'Other';
    const qty = item.quantity || 0;
    const val = qty * (item.purchasePrice || 0);
    const existing = categoryMap.get(cat) || { qty: 0, val: 0 };
    categoryMap.set(cat, { qty: existing.qty + qty, val: existing.val + val });
  });

  const categoryRows = Array.from(categoryMap.entries()).map(([cat, stats]) => [cat, stats.qty, stats.val]);
  const lowStockProducts = data
    .filter(d => (d.quantity || 0) <= (d.minimumQuantity || 0) && (d.quantity || 0) > 0)
    .map(d => [d.itemName, d.sku, d.quantity, d.minimumQuantity, d.warehouse]);
  const outOfStockProducts = data
    .filter(d => (d.quantity || 0) === 0)
    .map(d => [d.itemName, d.sku, d.warehouse, d.supplier]);
  const highestValueProducts = [...data]
    .map(d => ({ name: d.itemName, sku: d.sku, val: (d.quantity || 0) * (d.purchasePrice || 0), qty: d.quantity, price: d.purchasePrice }))
    .sort((a, b) => b.val - a.val)
    .slice(0, 5)
    .map(d => [d.name, d.sku, d.qty, d.price, d.val]);
  const lowestStockProducts = [...data]
    .filter(d => (d.quantity || 0) > 0)
    .sort((a, b) => (a.quantity || 0) - (b.quantity || 0))
    .slice(0, 5)
    .map(d => [d.itemName, d.sku, d.quantity, d.minimumQuantity, d.warehouse]);

  const analyticsAOA: any[][] = [
    ['INVENTORY ANALYTICS & DISTRIBUTION REPORT'],
    [''],
    ['STOCK & VALUE BY PRODUCT CATEGORY'],
    ['Category', 'Total Stock Quantity', 'Total Inventory Value']
  ];

  categoryRows.forEach(r => analyticsAOA.push(r));
  analyticsAOA.push(['']);
  analyticsAOA.push(['LOW STOCK PRODUCTS ALERT (EXCLUDING OUT OF STOCK)']);
  analyticsAOA.push(['Product Name', 'SKU', 'Current Stock', 'Minimum Stock Level', 'Warehouse']);
  
  if (lowStockProducts.length === 0) {
    analyticsAOA.push(['No low stock items detected.', '', '', '', '']);
  } else {
    lowStockProducts.forEach(r => analyticsAOA.push(r));
  }

  analyticsAOA.push(['']);
  analyticsAOA.push(['CRITICAL OUT OF STOCK PRODUCTS']);
  analyticsAOA.push(['Product Name', 'SKU', 'Warehouse', 'Supplier Name']);
  
  if (outOfStockProducts.length === 0) {
    analyticsAOA.push(['No out of stock items detected.', '', '', '']);
  } else {
    outOfStockProducts.forEach(r => analyticsAOA.push(r));
  }

  analyticsAOA.push(['']);
  analyticsAOA.push(['HIGHEST VALUE INVENTORY LINES (TOP 5 BY COST VALUE)']);
  analyticsAOA.push(['Product Name', 'SKU', 'Current Stock', 'Purchase Price', 'Total Inventory Value']);
  highestValueProducts.forEach(r => analyticsAOA.push(r));

  analyticsAOA.push(['']);
  analyticsAOA.push(['LOWEST STOCK INVENTORY LINES (TOP 5 BY CURRENT STOCK)']);
  analyticsAOA.push(['Product Name', 'SKU', 'Current Stock', 'Minimum Stock Level', 'Warehouse']);
  lowestStockProducts.forEach(r => analyticsAOA.push(r));

  const wsAnalytics = XLSX.utils.aoa_to_sheet(analyticsAOA);

  wsAnalytics['!cols'] = [{ wch: 35 }, { wch: 20 }, { wch: 20 }, { wch: 20 }, { wch: 25 }];

  // Format numbers in analytics tables
  Object.keys(wsAnalytics).forEach(cellRef => {
    if (cellRef.startsWith('!')) return;
    const cell = wsAnalytics[cellRef];
    if (cell && cell.t === 'n') {
      const cellDecoded = XLSX.utils.decode_cell(cellRef);
      const col = cellDecoded.c;
      const row = cellDecoded.r;
      
      // Stock by Category table formatting
      if (row >= 4 && row < 4 + categoryRows.length) {
        if (col === 1) cell.z = '#,##0';
        if (col === 2) cell.z = '₹#,##0.00';
      }
      
      // General format fallback for values
      if (cell.v > 10000) {
        cell.z = '₹#,##0.00';
      } else if (cell.v > 10) {
        // Quantities
        cell.z = '#,##0';
      }
    }
  });

  XLSX.utils.book_append_sheet(wb, wsAnalytics, 'Analytics');

  // ----------------------------------------------------
  // WRITE AND DOWNLOAD WORKBOOK
  // ----------------------------------------------------
  const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([wbout], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  const sanitizedFileName = `smartops_enterprise_inventory_${Date.now()}`;
  link.href = url;
  link.setAttribute('download', `${sanitizedFileName}.xlsx`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
